@startuml
USER -> View : Affiche option Config
View -> Controler : Demande de configuration
Controler -> Config : Charge config
Config -> Compilator : update config
USER -> View : Affiche fichier à charger
View -> Controler : Demande chargement de fichier
Controler -> Compilator : Complie le fichier
Compilator -> Controler : Transfert fichier compilé
Controler -> View : Affiche le résultat de la compilation

@enduml