@startuml
'https://plantuml.com/use-case-diagram
package Config{
(Create Config) as (cconfig)
(Load Config) as (lconfig)
}
(Compile) as (comp)

:User: --> (cconfig)
:User: --> (lconfig)
:User: --> (comp)

(cconfig) --> (Echap)
(cconfig) --> (Language)
(cconfig) --> (Path)
(cconfig) --> (Tag)

(comp) ..|> (Confirm)
:User: -d-> (Confirm)
(Confirm) ..|> (comp)

(Export Settings) as (exp)
(exp)<|..(comp)
(exp)---->:User:
:User:---->(exp)



@enduml